<Project>
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<LangVersion>14</LangVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<InvariantGlobalization>true</InvariantGlobalization>
	</PropertyGroup>
	<PropertyGroup Condition="'$(GEN_OPENAPI)' == 'false'">
		<OpenApiGenerateDocuments>false</OpenApiGenerateDocuments>
	</PropertyGroup>
</Project>