<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <!-- Production dependencies -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <!-- Version 3.* is not compatible with dotnet 10. Remaining on 2.* for now. -->
    <PackageVersion Include="Microsoft.Extensions.ApiDescription.Server" Version="10.0.10" />
    <PackageVersion Include="Microsoft.OpenApi" Version="2.11.0" />
  </ItemGroup>

  <!-- Development dependencies -->
  <ItemGroup>
  </ItemGroup>
</Project>