---
name: repo-template
services:
  app:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: app
    ports:
      - "127.0.0.1:3000:3000"
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: api
    ports:
      - "127.0.0.1:8080:8080"
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Database__Host=db
      - Database__Port=5432
      - Database__Username=postgres
      - Database__Password=postgres
      - Database__Database=postgres

  # TODO: need to consider whether to use this or some S3 compatable mock
  # Emulator for Azure Storage, used for local file uploads instead of sending
  # files to an actual server.
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.35.0
    container_name: azurite
    volumes:
      - ./tmp/data:/data
    ports:
      - "127.0.0.1:10000:10000"
      - "127.0.0.1:10001:10001"
      - "127.0.0.1:10002:10002"
    command: "azurite --blobHost 0.0.0.0 --debug /data/debug.log --skipApiVersionCheck"
    restart: unless-stopped
    hostname: azurite

  db:
    image: postgres:18-alpine
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Jaeger is used to collect OpenTelemetry. Visit the UI port to see traces
  # for the various applications.
  jaeger:
    image: jaegertracing/all-in-one:2.20.0
    container_name: jaeger
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9412
      COLLECTOR_OTLP_ENABLED: "true"
      QUERY_BASE_PATH: /telemetry
    ports:
      - "127.0.0.1:4317:4317"
      - "127.0.0.1:4318:4318"
      - "127.0.0.1:16686:16686"
    restart: unless-stopped

  kafka:
    image: apache/kafka:4.3.1
    container_name: kafka
    environment:
      # Configure listeners for both docker and host communication
      KAFKA_LISTENERS: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT
      # Settings required for KRaft mode
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091
      # Listener to use for broker-to-broker communication
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      # Required for a single node cluster
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "127.0.0.1:9092:9092"
    restart: unless-stopped
  kafka-ui:
    image: kafbat/kafka-ui:main
    container_name: kafka-ui
    depends_on:
      - kafka
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
    ports:
      - "127.0.0.1:9090:8080"

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "127.0.0.1:6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3