[tools]
	actionlint              = "latest"
	betterleaks             = "latest"
	biome                   = "2"
	dotnet                  = "10"
	hadolint                = "latest"
	hk                      = "latest"
	node                    = "26"
	"npm:dclint"            = "latest"
	"npm:markdownlint-cli"  = "latest"
	"npm:sort-package-json" = "latest"
	"pipx:sqlfluff"         = "latest"
	pnpm                    = "11"
	rust                    = "1.97"
	taplo                   = "latest"
	yamllint                = "latest"
