[tools]
	biome                  = "2"
	dotnet                 = "10"
	hk                     = "latest"
	node                   = "26"
	"npm:markdownlint-cli" = "latest"
	pnpm                   = "11"
	taplo                  = "latest"
