---
name: flare
services:
  server:
    build: nvflare_compose_server
    container_name: server
    volumes:
      - ./server:/workspace
      - nvflare_svc_persist:/tmp/nvflare/
    environment:
      NVFLARE_ORG: maritime
    ports:
      - "127.0.0.1:8002:8002"
      - "127.0.0.1:8003:8003"
  site-1:
    build: nvflare_compose_client
    container_name: site-1
    volumes:
      - ./site-1:/workspace
      - site-1_data:/data
    environment:
      NVFLARE_CLIENT_NAME: site-1
      NVFLARE_ORG: maritime
    ports:
      - "127.0.0.1:8091:8080"
  site-2:
    build: nvflare_compose_client
    container_name: site-2
    volumes:
      - ./site-2:/workspace
      - site-2_data:/data
    environment:
      NVFLARE_CLIENT_NAME: site-2
      NVFLARE_ORG: maritime
    ports:
      - "127.0.0.1:8092:8080"
  site-3:
    build: nvflare_compose_client
    container_name: site-3
    volumes:
      - ./site-3:/workspace
      - site-3_data:/data
    environment:
      NVFLARE_CLIENT_NAME: site-3
      NVFLARE_ORG: maritime
    ports:
      - "127.0.0.1:8093:8080"
volumes:
  nvflare_svc_persist: null
  site-1_data: null
  site-2_data: null
  site-3_data: null