name: build

on:
  merge_group:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:

jobs:
  docker-api:
    name: Build API Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/docker-build
        with:
          image-name: repo-template-api
          docker-file: api/Dockerfile

  docker-frontend:
    name: Build frontend Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/docker-build
        with:
          docker-context: frontend
          image-name: repo-template-frontend
          docker-file: Dockerfile