name: Docker - frontend

on:
  merge_group:
  push:
    branches:
      - main
    tags:
      - "frontend-v*"
  pull_request:

jobs:
  docker-frontend:
    name: Build frontend Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/docker-build
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image-name: repo-template-frontend
          docker-file: frontend/Dockerfile